version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "8050:8050"
    environment:
      KINGSDAY: "03_07_1341_BC"
      FLASK_APP: "app.py"
    volumes:
      - .:/app
