version: "3.9"

services:
  web:
    build: .
    image: tagless_app:latest
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0
